/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.NgoAccountantRole;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.NgoOfficeOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.SupplyWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lakshit S Talreja
 */
public class NgoAccountantPaymentJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem business;
    private NgoOfficeOrganization organization;
    private UserAccount account;
    private Enterprise enterprise;
    private SupplyWorkRequest request;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    /**
     * Creates new form NgoAccountantPaymentJPanel
     */
    public NgoAccountantPaymentJPanel(JPanel userProcessContainer, UserAccount account, NgoOfficeOrganization organization, Enterprise enterprise, EcoSystem business, SupplyWorkRequest request, Integer billAmount) {
        initComponents();
        jLabel3.setText(enterprise.getName());
        this.userProcessContainer = userProcessContainer;
        this.business = business;
        this.organization = organization;
        this.enterprise = enterprise;
        this.account = account;
        this.request = request;
        requestIDTextField.setText(request.getSuppReqId());
        populatJTable();
        billAmountTextField.setText(Integer.toString(request.getBillamount()));
        
    }
    
    private void populatJTable(){
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        String itemL = request.getItemList().toString();
        request.getItemList().forEach(item->{
            Object row[] = new Object[2];
            String arr[] = item.split(":");
            row[0] = arr[0];
            row[1] = arr[1];
            model.addRow(row);
        });
    }    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        payBillBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        requestIDTextField = new javax.swing.JTextField();
        billAmountTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel2.setText("Enterprise:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 24, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(226, 153, 0));
        jLabel3.setText("jLabel3");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 24, 97, -1));

        backJButton.setBackground(new java.awt.Color(0, 153, 255));
        backJButton.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 490, 130, 39));

        payBillBtn.setBackground(new java.awt.Color(0, 153, 255));
        payBillBtn.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        payBillBtn.setText("Pay Bill");
        payBillBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payBillBtnActionPerformed(evt);
            }
        });
        add(payBillBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, 300, 45));

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel1.setText("Process Payment");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 71, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel4.setText("Request ID: ");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 128, -1, 30));

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel5.setText("Item List: ");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, -1, -1));

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel6.setText("Bill Amount: ");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, -1, -1));

        requestIDTextField.setEditable(false);
        requestIDTextField.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        requestIDTextField.setEnabled(false);
        add(requestIDTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 150, -1));

        billAmountTextField.setEditable(false);
        billAmountTextField.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        billAmountTextField.setEnabled(false);
        add(billAmountTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, 150, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "Item Type", "Item Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(20);
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 300, 130));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void payBillBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payBillBtnActionPerformed
        request.setReceiver(account);
        request.setStatus("Bill paid");
        request.setResolveDate(new Date());
        dB4OUtil.storeSystem(business);
        JOptionPane.showMessageDialog(null, "Bill Paid");
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_payBillBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField billAmountTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton payBillBtn;
    private javax.swing.JTextField requestIDTextField;
    // End of variables declaration//GEN-END:variables

    
}
