/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
*/
package userinterface.FieldWorkerRole;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.PetShelterOrganization;
import Business.POJO.Pet;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.PetHealthCheckUpRequest;
import Business.WorkQueue.PetHealthCheckUpRequest.urgency;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author rishijatania
 */
public class FieldWorkerPetHealthCheckUpJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private EcoSystem business;
    private PetShelterOrganization petShelterOrganization;
    private UserAccount account;
    private Enterprise enterprise;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    private Pet pet;
    /**
     * Creates new form FieldWorkerPetHealthCheckUpJPanel
     */
    public FieldWorkerPetHealthCheckUpJPanel(JPanel userProcessContainer, UserAccount account, PetShelterOrganization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;
        this.petShelterOrganization = organization;
        this.account = account;
        this.enterprise=enterprise;
        for (urgency type : urgency.values()) {
            urgencyCmb.addItem(type.getValue());
        }
        reportIDTextField.setText(Integer.toString(business.getIdGenInstance().getReqId()));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        animalTypeTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        reportIDTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        reportedPetTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        searchBtn = new javax.swing.JButton();
        reqBtn = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        CommentsTextField1 = new javax.swing.JTextField();
        urgencyCmb = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        animalTypeTextField.setEditable(false);
        animalTypeTextField.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        animalTypeTextField.setEnabled(false);
        animalTypeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                animalTypeTextFieldActionPerformed(evt);
            }
        });
        add(animalTypeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 140, -1));

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel7.setText("Urgency:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, -1, -1));

        reportIDTextField.setEditable(false);
        reportIDTextField.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        reportIDTextField.setEnabled(false);
        reportIDTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportIDTextFieldActionPerformed(evt);
            }
        });
        add(reportIDTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 140, -1));

        jLabel10.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel10.setText("Pet ID:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 100, 30));

        reportedPetTextField.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        reportedPetTextField.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                reportedPetTextFieldInputMethodTextChanged(evt);
            }
        });
        reportedPetTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportedPetTextFieldActionPerformed(evt);
            }
        });
        add(reportedPetTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 140, -1));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel2.setText("Report ID:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, -1, -1));

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel5.setText("Animal Type: ");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, -1, -1));

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel1.setText("Pet Health Check Request");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, 40));

        searchBtn.setBackground(new java.awt.Color(0, 153, 255));
        searchBtn.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });
        add(searchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, -1, -1));

        reqBtn.setBackground(new java.awt.Color(0, 153, 255));
        reqBtn.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        reqBtn.setText("Raise Request");
        reqBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reqBtnActionPerformed(evt);
            }
        });
        add(reqBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 430, 170, 40));

        backJButton.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, -1, 40));

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel8.setText("Comments:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, -1, -1));

        CommentsTextField1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        CommentsTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CommentsTextField1ActionPerformed(evt);
            }
        });
        add(CommentsTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, 140, -1));

        urgencyCmb.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        urgencyCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urgencyCmbActionPerformed(evt);
            }
        });
        add(urgencyCmb, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 140, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void animalTypeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_animalTypeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_animalTypeTextFieldActionPerformed

    private void reportIDTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportIDTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reportIDTextFieldActionPerformed

    private void reportedPetTextFieldInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_reportedPetTextFieldInputMethodTextChanged
        // TODO add your handling code here:
        enableSearchBtn();
    }//GEN-LAST:event_reportedPetTextFieldInputMethodTextChanged

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        pet=business.getPetDirInstance().getListOfPets().stream().filter(item->item.getPetId().equalsIgnoreCase(reportedPetTextField.getText()))
                .findFirst()
                .orElse(null);
        if(pet==null){
            JOptionPane.showMessageDialog(null, "No such pet Found");
        }
        else{
            animalTypeTextField.setText(pet.getAnimalType());
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void reportedPetTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportedPetTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reportedPetTextFieldActionPerformed

    private void reqBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reqBtnActionPerformed
        // TODO add your handling code here:
        if(reportedPetTextField.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Pet not selected");
            return;
        }
        Date date = new Date();
        PetHealthCheckUpRequest req=new PetHealthCheckUpRequest();
        req.setPet(pet);
        req.setRequestDate(date);
        req.setUrgency(urgencyCmb.getSelectedItem().toString());
        req.setComments(CommentsTextField1.getText());
        req.setRequestId(reportIDTextField.getText());
        req.setStatus("New");
        req.setSender(account);
        dB4OUtil.storeSystem(business);
        account.getWorkQueue().getWorkRequestList().add(req);
        petShelterOrganization.getWorkQueue().getWorkRequestList().add(req);
        JOptionPane.showMessageDialog(null, "Request raised");
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_reqBtnActionPerformed

    private void CommentsTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CommentsTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CommentsTextField1ActionPerformed
    
    private void urgencyCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urgencyCmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_urgencyCmbActionPerformed
    
    public void enableSearchBtn(){
        searchBtn.setEnabled(true);
        reqBtn.setEnabled(false);
    }
    
    public void disnableSearchBtn(){
        searchBtn.setEnabled(false);
        reqBtn.setEnabled(true);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CommentsTextField1;
    private javax.swing.JTextField animalTypeTextField;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField reportIDTextField;
    private javax.swing.JTextField reportedPetTextField;
    private javax.swing.JButton reqBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JComboBox<String> urgencyCmb;
    // End of variables declaration//GEN-END:variables
}
