/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.FieldWorkerRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.PetShelterOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;


public class FieldWorkerWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem business;
    private UserAccount account;
    private PetShelterOrganization organization;
    private Enterprise enterprise;
    
    public FieldWorkerWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise,EcoSystem business) {
        initComponents();
        jLabel3.setText(enterprise.getName());
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.business = business;
        this.organization = (PetShelterOrganization)organization;
        this.enterprise = enterprise;
        this.business = business;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        FieldWorkerDBBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel1.setText("Field Worker Work Area");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, -1, -1));

        FieldWorkerDBBtn.setBackground(new java.awt.Color(0, 153, 255));
        FieldWorkerDBBtn.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        FieldWorkerDBBtn.setText("DashBoard");
        FieldWorkerDBBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldWorkerDBBtnActionPerformed(evt);
            }
        });
        add(FieldWorkerDBBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 170, 50));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel2.setText("Enterprise:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(226, 153, 0));
        jLabel3.setText("jLabel3");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void FieldWorkerDBBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldWorkerDBBtnActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("FieldWorkerDashBoardJPanel", new FieldWorkerDashBoardJPanel(userProcessContainer,account,organization,enterprise ,business));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_FieldWorkerDBBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FieldWorkerDBBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
