/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.WardenRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.PetShelterOrganization;
import Business.POJO.Pet;
import Business.Role.FieldWorkerRole;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.ReportStrayAnimalRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.apache.log4j.Logger;

/**
 *
 * @author Lakshit S Talreja
 */
public class AssignFieldWorkerJPanel extends javax.swing.JPanel {

    
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private PetShelterOrganization organization; 
    private PetShelterOrganization petShelterOrganization = new PetShelterOrganization();
    private Enterprise enterprise;
    private EcoSystem business;
    private Pet pet;
    private WorkRequest workQ;
    private final Logger logger = Logger.getLogger(this.getClass());
    /**
     * Creates new form RegisterAnimalJPanel
     */
    public AssignFieldWorkerJPanel(JPanel userProcessContainer, UserAccount account, PetShelterOrganization organization, Enterprise enterprise, EcoSystem business, WorkRequest workQ) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.business = business;
        this.workQ = workQ;
        populateWorkQ();
        populateComboBox();
        // System.out.println(workQ);


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        reportIDTextField = new javax.swing.JTextField();
        addressTextField = new javax.swing.JTextField();
        zipTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        commentsTextArea = new javax.swing.JTextArea();
        submitReportBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        animalTypeTextField = new javax.swing.JTextField();
        issueTypeTextField = new javax.swing.JTextField();
        urgencyTypeTextField = new javax.swing.JTextField();
        cityTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        reportedUserTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        fieldWorkerComboBox = new javax.swing.JComboBox<>();
        backJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel1.setText("Assign to Field Worker");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(468, 22, -1, -1));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel2.setText("Report ID:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 94, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel3.setText("Street Address:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 272, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel4.setText("City:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 272, -1, -1));

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel6.setText("Zip:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 272, -1, -1));

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel7.setText("Issue:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(538, 205, -1, -1));

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel8.setText("Urgency:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(741, 205, -1, -1));

        jLabel9.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel9.setText("Comments:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 339, -1, -1));

        reportIDTextField.setEditable(false);
        reportIDTextField.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        reportIDTextField.setEnabled(false);
        reportIDTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportIDTextFieldActionPerformed(evt);
            }
        });
        add(reportIDTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 91, 114, -1));

        addressTextField.setEditable(false);
        addressTextField.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        addressTextField.setEnabled(false);
        add(addressTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 269, 118, -1));

        zipTextField.setEditable(false);
        zipTextField.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        zipTextField.setEnabled(false);
        zipTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zipTextFieldActionPerformed(evt);
            }
        });
        add(zipTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(829, 202, 117, -1));

        commentsTextArea.setEditable(false);
        commentsTextArea.setColumns(20);
        commentsTextArea.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        commentsTextArea.setRows(5);
        commentsTextArea.setEnabled(false);
        jScrollPane1.setViewportView(commentsTextArea);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 330, 181, 74));

        submitReportBtn.setBackground(new java.awt.Color(0, 153, 255));
        submitReportBtn.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        submitReportBtn.setText("Submit");
        submitReportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitReportBtnActionPerformed(evt);
            }
        });
        add(submitReportBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(593, 524, 130, 40));

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel5.setText("Animal Type: ");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 205, -1, -1));

        animalTypeTextField.setEditable(false);
        animalTypeTextField.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        animalTypeTextField.setEnabled(false);
        animalTypeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                animalTypeTextFieldActionPerformed(evt);
            }
        });
        add(animalTypeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 202, 117, -1));

        issueTypeTextField.setEditable(false);
        issueTypeTextField.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        issueTypeTextField.setEnabled(false);
        issueTypeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issueTypeTextFieldActionPerformed(evt);
            }
        });
        add(issueTypeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(597, 202, 127, -1));

        urgencyTypeTextField.setEditable(false);
        urgencyTypeTextField.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        urgencyTypeTextField.setEnabled(false);
        urgencyTypeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urgencyTypeTextFieldActionPerformed(evt);
            }
        });
        add(urgencyTypeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(828, 269, 118, -1));

        cityTextField.setEditable(false);
        cityTextField.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        cityTextField.setEnabled(false);
        cityTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityTextFieldActionPerformed(evt);
            }
        });
        add(cityTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(595, 269, 128, -1));

        jButton1.setBackground(new java.awt.Color(0, 153, 255));
        jButton1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jButton1.setText("Edit Comments");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 524, -1, 40));

        jLabel10.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel10.setText("Reported User:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 147, -1, -1));

        reportedUserTextField.setEditable(false);
        reportedUserTextField.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        reportedUserTextField.setEnabled(false);
        add(reportedUserTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 144, 117, -1));

        jLabel11.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel11.setText("Assign to Field Worker: ");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 436, -1, -1));

        fieldWorkerComboBox.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        fieldWorkerComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(fieldWorkerComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 433, 181, -1));

        backJButton.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, -1, 40));
    }// </editor-fold>//GEN-END:initComponents
    private void populateWorkQ(){
        //reportIDTextField.setText(Integer.toString(((ReportStrayAnimalRequest) workQ).getReportId()));
        reportIDTextField.setText(((ReportStrayAnimalRequest) workQ).getReportId());
        animalTypeTextField.setText(((ReportStrayAnimalRequest) workQ).getAnimalType());
        addressTextField.setText(((ReportStrayAnimalRequest) workQ).getStreet());
        cityTextField.setText(((ReportStrayAnimalRequest) workQ).getCity());
        zipTextField.setText(Integer.toString(((ReportStrayAnimalRequest) workQ).getZipCode()));
        issueTypeTextField.setText(((ReportStrayAnimalRequest) workQ).getIssueType());
        urgencyTypeTextField.setText(((ReportStrayAnimalRequest) workQ).getUrgencyType());
        commentsTextArea.setText(((ReportStrayAnimalRequest) workQ).getComments());
        reportedUserTextField.setText(((ReportStrayAnimalRequest) workQ).getUsername());
    }
    
    private void populateComboBox() {
        fieldWorkerComboBox.removeAllItems();
        
        for (UserAccount user : organization.getUserAccountDirectory().getUserAccountList()) {
            if(user.getRole() instanceof FieldWorkerRole){
                fieldWorkerComboBox.addItem(user.getUsername());
                //System.out.println(user.getUsername());
            }
            
        }
    }
    
    
    
    private void reportIDTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportIDTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reportIDTextFieldActionPerformed

    private void submitReportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitReportBtnActionPerformed
        // TODO add your handling code here:
        //System.out.println(fieldWorkerComboBox.getSelectedItem());
        for (UserAccount user : organization.getUserAccountDirectory().getUserAccountList()) {
            if(user.getRole() instanceof FieldWorkerRole){
                if(user.getUsername().equals(fieldWorkerComboBox.getSelectedItem())){
                    user.getWorkQueue().getWorkRequestList().add(workQ);
                    ((ReportStrayAnimalRequest) workQ).setComments(commentsTextArea.getText());
                    logger.info(workQ + " assigned to field worker " + user.getUsername());
            }
                
         }
            
        }
        JOptionPane.showMessageDialog(null, "Submitted successfully");
        workQ.setStatus("FieldWorker Assigned");
        workQ.setReceiver(userAccount);
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_submitReportBtnActionPerformed

    private void animalTypeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_animalTypeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_animalTypeTextFieldActionPerformed

    private void issueTypeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issueTypeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_issueTypeTextFieldActionPerformed

    private void urgencyTypeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urgencyTypeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_urgencyTypeTextFieldActionPerformed

    private void cityTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityTextFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        commentsTextArea.setEnabled(true);
        commentsTextArea.setEditable(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void zipTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zipTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zipTextFieldActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressTextField;
    private javax.swing.JTextField animalTypeTextField;
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField cityTextField;
    private javax.swing.JTextArea commentsTextArea;
    private javax.swing.JComboBox<String> fieldWorkerComboBox;
    private javax.swing.JTextField issueTypeTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField reportIDTextField;
    private javax.swing.JTextField reportedUserTextField;
    private javax.swing.JButton submitReportBtn;
    private javax.swing.JTextField urgencyTypeTextField;
    private javax.swing.JTextField zipTextField;
    // End of variables declaration//GEN-END:variables
}
