/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.WardenRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.NgoOfficeOrganization;
import Business.Organization.Organization;
import Business.Organization.PetShelterOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import org.apache.log4j.Logger;

/**
 *
 * @author Suraj PC
 */
public class WardenWorkAreaJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private EcoSystem business;
    private PetShelterOrganization organization;
    private Enterprise enterprise;
    private UserAccount account;
    private final Logger logger = Logger.getLogger(this.getClass());
    /**
     * Creates new form HCAdminWorkAreaJPanel
     */
    public WardenWorkAreaJPanel(JPanel userProcessContainer, UserAccount account,PetShelterOrganization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        jLabel3.setText(enterprise.getName());
        this.userProcessContainer=userProcessContainer;
        this.business=business;
        this.organization=organization;
        this.enterprise=enterprise;
        this.account=account;
        logger.info(account + " Warden logged into WorkAreaJPanel");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel1.setText("Warden Work Area");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 79, -1, -1));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel2.setText("Enterprise:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 23, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(226, 153, 0));
        jLabel3.setText("jLabel3");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 23, 97, -1));

        jButton3.setBackground(new java.awt.Color(0, 153, 255));
        jButton3.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jButton3.setText("DashBoard");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 177, 200, 60));

        jButton4.setBackground(new java.awt.Color(0, 153, 255));
        jButton4.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jButton4.setText("Request for Supplies");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 200, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        logger.info(account + " Warden clicked on Dashboard JButton");
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("WardenDashBoardJPanel", new WardenDashBoardJPanel(userProcessContainer,account,organization,enterprise ,business));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        logger.info(account + " Warden clicked on Request for Supplies JButton");
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        Organization org = null;
        for (Organization organization1 : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization1 instanceof NgoOfficeOrganization){
                org = organization1;
                break;
            }
        }
        if (org!=null){
            userProcessContainer.add("SupplyRequestJPanel", new SupplyRequestJPanel(userProcessContainer,account,(NgoOfficeOrganization)org,organization,enterprise ,business));
            layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
